services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      - hogwartsnet

  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    container_name: portal
    networks:
      - hogwartsnet

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      # Certificados SSL do ISP
      - ./proxy/ssl/hogwarts.br.crt:/etc/nginx/ssl/hogwarts.br.crt:ro
      - ./proxy/ssl/hogwarts.br.key:/etc/nginx/ssl/hogwarts.br.key:ro

      # Certificados SSL do cliente Sonserina (apenas leitura)
      - ../clientes/sonserina/proxy/ssl/sonserina.br.crt:/etc/nginx/ssl/sonserina.br.crt:ro
      - ../clientes/sonserina/proxy/ssl/sonserina.br.key:/etc/nginx/ssl/sonserina.br.key:ro

      # Certificados SSL do cliente grifinoria (apenas leitura)
      - ../clientes/grifinoria/proxy/ssl/grifinoria.br.crt:/etc/nginx/ssl/grifinoria.br.crt:ro
      - ../clientes/grifinoria/proxy/ssl/grifinoria.br.key:/etc/nginx/ssl/grifinoria.br.key:ro

      
      # Certificados SSL do cliente corvinal (apenas leitura)
      - ../clientes/corvinal/proxy/ssl/corvinal.br.crt:/etc/nginx/ssl/corvinal.br.crt:ro
      - ../clientes/corvinal/proxy/ssl/corvinal.br.key:/etc/nginx/ssl/corvinal.br.key:ro
      
      # Configuração do nginx e HTML
      - ./proxy/index.html:/usr/share/nginx/html/index.html:ro
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - hogwartsnet
      - sonserinabridge
      - grifinoriabridge
      - corvinalbridge
    depends_on:
      - webmail

  mail:
    build:
      context: ./email
      dockerfile: Dockerfile
    image: email
    container_name: email
    hostname: mail.hogwarts.br
    restart: always
    environment:
      - DOMAIN=hogwarts.br
    ports:
      - "25:25/tcp"
      - "587:587/tcp"
      - "465:465/tcp"
      - "993:993/tcp"
    volumes:
      - ./proxy/ssl/hogwarts.br.crt:/etc/ssl/certs/hogwarts.br.crt:ro
      - ./proxy/ssl/hogwarts.br.key:/etc/ssl/private/hogwarts.br.key:ro
      - ./proxy/ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
      - maildata:/maildata
    networks:
      - hogwartsnet

  webmail:
    build: ./webmail       
    container_name: webmail
    depends_on:
      - mail
    volumes:
      - ./webmail/config/config.inc.php:/var/roundcube/config/config.inc.php:ro
    expose:
      - 80
    networks:
      - hogwartsnet

networks:
  hogwartsnet:
    external: true
  sonserinanet:
    external: true
  grifinorianet:
    external: true
  corvinalnet:
    external: true

  sonserinabridge:
      external: true
  grifinoriabridge:
      external: true
  corvinalbridge:
      external: true    
    


volumes:
  roundcube_data:
    driver: local
  maildata:
    driver: local
  postgres_data:
    driver: local
